# Generated by Django 4.0.3 on 2022-03-24 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=50)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=50)),
                ('date_released', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 21, 6, 10, 413058))),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='product_pics')),
            ],
        ),
    ]
